### ISSUE TITLE
Port notification upon job completion functionality from private repo

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/ngen-cal#103]
Expand ngen-cal utilities, consider some simple event notifications which allow user/caller scripts to do what they see fit.

Do not leave user property in Evaluatable or EvaluationOptions!

**Comment by aaraney** [comment]
Related to https://github.com/NOAA-OWP/ngen-cal/pull/126

**Comment by aaraney** [comment]
I looked into how we might do this yesterday using [this pure python](https://docs.python.org/3/library/email.examples.html#email-examples) example and how we might do this for [gmail](https://developers.google.com/gmail/api/guides/sending). The more that I look into it and think about it, I think we can just provide an example of how to do this using a plugin, but I don't think this is something that we will want to maintain as a feature longterm. I think we can support simple the SMTP case, but that is less and less applicable these days (e.g. MFA / BioAuth requirements).

**Comment by hellkite500** [comment]
Implementing as an `ngen_cal_finish` plugin hook in a top level `example_plugins` or even `plugins` directory under `python/ngen_cal`.  Things to consider: how to provide name/path to plugins in config.yaml, installed modules vs local file modules, ect.

**Comment by aaraney** [comment]
Yeah, im not sold that we need to worry / consider those things. At the end of the day, it all comes down to how python imports modules. So, the three main options are:

- Run `ngen.cal` from the same directory that contains your plugin. Then you can just `ngen_cal_plugin` (note, drop `.py`) for a function based plugin or `ngen_cal_plugin.MyPlugin` if it's a class based plugin.
- Using `PYTHONPATH` to add a directory for python to search (i.e. `PYTHONPATH=~/plugins python -m ngen.cal config.yaml`)
- Creating an installable plugin (i.e. define `pyproject.toml`). Then you can just provide the module path in the config.

**Comment by aaraney** [comment]
Closing this b.c. the `ngen_cal_finish` plugin satisfies what is required implement this feature. Its of our opinion that a notification is workflow specific and should be implemented as a custom or installable plugin.
