### ISSUE TITLE
Output all simulated hydrographs for comparison

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/ngen-cal#11]
For diagnosing how parameters drive model behavior it would be useful to have all simulated hydrographs saved as output during calibration.

## Current behavior
Calibration script outputs hydrograph corresponding to best parameter set.

## Expected behavior
Output hydrographs for all parameter sets, either as default behavior or as option. (The latter is likely more useful as output will get large as study domain expands.)

## Steps to replicate behavior (include URLs)

1. Run calibration script as-is.

**Comment by hellkite500** [comment]
How many iterations would you want to plot at once?  It is possible to save them all, but might not be very disk friendly to so naively.   I can definitely add some tooling around it, but might want to think of a better long term strategy.

**Comment by hellkite500** [comment]
An option/plugin now exists which allows model outputs from each iteration to be copied/saved for future evaluation.

Under the `model` config key, you can simply add:

``` yaml
    plugins: ["ngen.cal.ngen_hooks.ngen_output.NgenSaveOutput"]
```
or
```yaml
    plugins:
        - "ngen.cal.ngen_hooks.ngen_output.NgenSaveOutput"
```
and under the working directory for the runs, ngen outputs for each iteration will exist under subdirectories `output_1`, `output_2`, `output_N`, for all `N` iterations.
