### ISSUE TITLE
Include logic to save best results

### ISSUE THREAD

**Issue by lcunha0118** [NOAA-OWP/ngen-cal#21]
Right now only the last result is saved. It would be helpful to save the best result, and also the realization file for best results.

**Comment by hellkite500** [comment]
partially addressed with NgenSaveOutput plugin (#130) which allows saving all model outputs for each iteration.  Though I don't think this copies the realization, which would be helpful to do.  May also be worth developing a similar plugin which can track the best results and only save those.  This would require some additional meta data to passed along the `iteration_finish` hook.  @aaraney this would be another good use case to think about as we continue to refine the approach.

**Comment by aaraney** [comment]
Yeah, you should be able to create a ["wrapped"](https://pluggy.readthedocs.io/en/stable/#wrappers) `ngen_cal_model_output` plugin to save each model's t-route output. Then use the parquet file of calibration results and retrieve the corresponding iteration. I think all the pieces are there to make this possible.
