### ISSUE TITLE
Typo in formulation model constraint

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/ngen-cal#32]
https://github.com/NOAA-OWP/ngen-cal/blob/fdca5620efc1f021af9ce044aab2e4852a81792a/python/ngen_conf/src/ngen/config/formulation.py#L8

This should be `discriminator`. Likewise, the discriminator should be `model_type_name` not `model_name`. `model_type_name` is the alias for `model_name`, meaning `model_type_name` is the key in the configuration file.

Edit:

While this was an issue, by correctly spelling `discriminator`, this forced all `model_type_name` fields to be type `Literal`. This is okay in most cases, however it is not desirable for `MultiBMI`. `MultiBMI`'s `model_type_name` field should not be constrained like the other BMI model pydantic model types.

However, there still needs to be a way to determine the correct pydantic model variant from the union of formulations, `KnownFormulations`. The `name` and `model_type_name` fields are used for this purpose. `name` corresponds the bmi adapter name used by that model (e.g. `bmi_fortran`) and `model_type_name` roughly corresponds to the model name (e.g. `NoahOWP`). For non-multi bmi models, the `name` _and_ `model_type_name` are constant values (e.g. `bmi_fortran` and `NoahOWP` for the `NoahOWP` pydantic model). In the case of the `MultiBMI` pydantic model, only _name_ is a constant value, `bmi_multi`, `model_type_name` can be any valid string.

However, it feels tedious that it would be required to specify these constants when programmatically creating a for example, a `NoahOWP` instance. For this reason, these constants _are not required_ when creating a `KnownFormulations` type. Likewise, it is possible to pass a `KnownFormulations` instance when creating a `Formulation` object. However, to deserialized into `Formulation` object, it _is_ required that `name` _and_ `model_type_name` are present for non-multi bmi types and ,potentially only, `name` it equals bmi_multi`.

**Comment by aaraney** [comment]
I can get a PR in for the on Monday. If I forget, just ping me.

**Comment by hellkite500** [comment]
@aaraney ping?
