### ISSUE TITLE
Formalize Crosswalk format

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/ngen-cal#38]
I ran into an issue performing a calibration that resulted in a `RuntimeError: Currently only a single nexus in the hydrfabric can be gaged` exception. @mattw-nws, shared a patch to get around this issue, however it appears we can avoid this error and improve error handling if we are to formalize a crosswalk format.

At the present it appears the expected format is:

```json5
{
"(cat|wb)-[0-9]+": {
  "Gage_no": int
  },
  ...
}

```

https://github.com/NOAA-OWP/ngen-cal/blob/55968df3fe83671c52d40ce73c4ef8795991b237/python/ngen_cal/src/ngen/cal/ngen.py#L122

@hellkite500, are you open to introducing a pydantic model(s) to handle deserializing crosswalk files? I think something like the following will work:

```python
from pydantic import BaseModel, Field, constr

# typing imports
from typing import Dict

class CrosswalkItem(BaseModel):
  gage_no: int = Field(..., alias="Gage_no")

class Crosswalk(BaseModel):
  __root__: Dict[constr(regex="^(cat|wb)-[0-9]+$"), CrosswalkItem]

```

**Comment by aaraney** [comment]
We now use the `flowpath-attributes` (new hf) or `flowpath_attributes` (old hf) table in the gpkg hf to perform the crosswalk.

**Comment by hellkite500** [comment]
> @aaraney | @hellkite500 
> Is this <RuntimeError: Currently only a single nexus in the hydrfabric can be gaged, set the eval_feature key to pick one.> been resolved? Could you please direct me to the right commit of ngen-cal, if this issue has been resolved. 

#129 addresses this specific issue
