### ISSUE TITLE
Why is CFE's "water_potential_evaporation_flux": "EVAPOTRANS" commented out?

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/ngen-cal#61]
> I am not sure why this is commented out, if we are not explicitly running any PET module then CFE takes PET (i.e., `EVAPOTRANS`) from NOAH_OM as an input or am I missing something here
`#"water_potential_evaporation_flux": "EVAPOTRANS",`

_Originally posted by @ajkhattak in https://github.com/NOAA-OWP/ngen-cal/issues/49#issuecomment-1645704721_ 

@hellkite500, @ajkhattak raised this question in reviewing #49. Can you have a look at this an add some your insight?

**Comment by hellkite500** [comment]
The config `cfe.py` is used to generate ngen realization config blocks for a CFE model.  The section in question here is the `_variables_name_map` which is simply a *default* name map to put into generated config files (unless it is replaced/updated by other code before serialization...).  This is commented out simply becuase it didn't seem to lend to a reasonable default given that there is more than one way currently to provide PET to a module.
