### ISSUE TITLE
Observation and Model units don't correspond

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen-cal#7]
Observation values coming from hydrolocation (NWIS) are in f^3/S (cubic feet per second) and model outputs are in m^3/s (cubic meters per second).

This either needs adjusted here or upstream in hypy nwis location.  Regardless of where it gets addressed, needs to be better documented.

**Comment by stcui007** [comment]
Could it be possible that the actual units from ngen output at the moment
is m/s? I don't see catchment_area_km2 (= 5.0 hard coded) being used in
ngen code?
