### ISSUE TITLE
ngen-config Update model_param spec

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen-cal#72]
https://github.com/NOAA-OWP/ngen-cal/blob/3a170b81632050381f14c374b1eaeac06da0f607/python/ngen_conf/src/ngen/config/bmi_formulation.py#L45C5-L45C17

ngen now supports a model param mapping to link model params to hydrofabric feature attributes.

The config structure can be seen [here in this test code](https://github.com/NOAA-OWP/ngen/blob/1dcd25596596f5a2c2aef172fc53e12fecd101f9/test/realizations/Formulation_Manager_Test.cpp#L524).

The config schema should be updated to reflect this change and properly validate/generate configs that may have this structure.

**Comment by aaraney** [comment]
Thanks for pinging me, @hellkite500. From a quick glance it looks like `model_params` can now be one either `None` (unspecified), `Mapping[str, str]` (current specified form), or a `Mapping[str, Mapping[str, str]]`. So as a type hint that would look like:

```python
    model_params: Optional[Mapping[str, Union[str, Mapping[str, str]]]]
```

Is it valid for the inner associated value types to be either `str` _or_ `Mapping[str, str]` in the same outer mapping type? Or are the two variant exclusive? For example is this allowed?

```json
{
    "model_params": {
        "str_kv": "str_v",
        "map_kv": {
            "map_k": "map_v"
        }
    }
}
```

Or are the following two examples only allowed?

```json
{
    "model_params": {
        "str_kv": "str_v"
    }
}
```

```json
{
    "model_params": {
        "map_kv": {
            "map_k": "map_v"
        }
    }
}
```

**Comment by hellkite500** [comment]
It can be mixed.  Though there is a current constraint that if it is a `Mapping` it should be in the form of
```json
"model_params": {
    "key": {
        "source" : "source_value",
        "from" : "from_value"
    }
}
```
So we should probably define a custom linking type which has strict `source` and `from` keys, and the type would become
```Optional[ Mapping[ str, Union[ str, LinkType] ] ]``` 
I'm also not convinced that `str` is the only type...I'm pretty sure it can be numeric or list as well, just to complicate things a bit haha.

**Comment by aaraney** [comment]
Thanks for the clarification!

> I'm also not convinced that `str` is the only type...I'm pretty sure it can be numeric or list as well, just to complicate things a bit haha.

If you are talking about the keys, only `str`'s are allowed as keys in json.

**Comment by hellkite500** [comment]
I'm refering to the values, e.g.
```json
"model_params": {
    "param1": 4.2,
    "param2": [ 4, 2 ]
}
```

**Comment by aaraney** [comment]
Ah, so sequences are also supported?

**Comment by aaraney** [comment]
I would assume sequences of numbers or str's?

**Comment by hellkite500** [comment]
I'm not sure str is actually supported at all, I'll have to check the backend NGEN code haha

**Comment by hellkite500** [comment]
https://github.com/NOAA-OWP/ngen/blob/1dcd25596596f5a2c2aef172fc53e12fecd101f9/include/realizations/catchment/Bmi_Module_Formulation.hpp#L574

Found it, not sure why "str" was here in the first place, unless there was some type conversion happening somewhere else in ngen...still looking a bit

**Comment by aaraney** [comment]
@hellkite500, thanks for digging into that and also pulling links. Im sure either we or someone else will appreciate the paper trail in the future.

Looking at the NextGen link you sent, it looks like the appropriate type hint should be:

```python
Numeric = Union[int, float]
MODEL_PARAMS_T = Optional[Mapping[str, Union[Numeric, Sequence[Numeric], Mapping[str, LinkType]]]]
```
