### ISSUE TITLE
Port remaining configuration utilities from private repo

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/ngen-cal#98]
Partitally addressed with #97 for adding support to ngen_conf for new modules.

Additional configuration mechanics need to be evaluated from the createInput package and aligned with ngen-cal configuation.py where it makes sense.

Additional customizations and configuration creation *may* be suitable for a user script.

**Comment by aaraney** [comment]
Having reviewed the `createInput` package, IMO I don't think we _need_ to port it. I think it falls under the category of personal workflow and im opposed to changing what is already working for someone. Instead, we can take some of the ideas from the workflow and create a full end to end example of using `ngen.config`, `ngen.config_gen`, and `ngen.cal` to conduct a calibration exercise, but to me _that_ is not in scope for this particular task. Ive created #114 to track producing that example.

I am closing this as completed, but please reopen have a differing opinion about `createInput` _or_ think that the e2e example is in scope.
